// Tip: Interface defining the structure of a Delivery object for consistent data handling
export interface Delivery {
  // Tip: Unique identifier for each delivery, auto-generated by backend
  id: number;
  // Tip: Customer's full name for identification and communication
  name: string;
  // Tip: Contact phone number in international format for coordination
  phone: string;
  // Tip: Delivery address or Google Maps URL for accurate location
  location: string;
  // Tip: Description of the item being delivered, including fragility details
  item: string;
  // Tip: Scheduled delivery date in YYYY-MM-DD format
  deliveryDate: string;
  // Tip: Package size category (Small, Medium, Large, Extra Large)
  packageSize: string;
  // Tip: Additional notes for special instructions or handling requirements
  notes: string;
}
